### ISSUE TITLE
[New cleanup rules] broken link 

### ISSUE THREAD

**Issue by GreenAA** [constup/garbage-cleaner-powershell#1]
hi 
broken link 

https://github.com/constup/garbage-cleaner/releases 

Note: All cleanup list rules must follow the [JSON Schema](https://github.com/constup/garbage-cleaner-powershell/blob/master/cleanup-list.schema.json). Make sure to read [Contributing to the cleanup list](https://github.com/constup/garbage-cleaner-powershell/blob/master/CONTRIBUTING.adoc#contributing-to-the-cleanup-list) before opening an issue.

Note: If you do not have a clear list of cleanup rules and want to request an expansion of the cleanup list, please open a new **Feature request** instead.

**Cleanup list rules (in JSON format)**
```json
```
**Do any of your cleanup rules require new categories? (yes/no)**

**If your cleanup rules require new categories, list them here and add a short reason why they should be introduced as separate categories.**

**Do any of your cleanup rules require new entity categories? (yes/no)**

**If your cleanup rules require new entity categories, list them here and add a short reason why the should be introduced as separate entity categories.**

**Comment by constup** [comment]
Fixed in 0.1.0.
